### ISSUE TITLE
TypeError: GenerationMixin._sample() missing 1 required positional argument: 'logits_warper'

### ISSUE THREAD

**Issue by jasonngap1** [huggingface/speech-to-speech#14]
```
python s2s_pipeline.py \
	--recv_host 0.0.0.0 \
	--send_host 0.0.0.0 \
	--lm_model_name microsoft/Phi-3-mini-4k-instruct \
	--init_chat_role system \
	--stt_compile_mode reduce-overhead \
	--tts_compile_mode default 
```

Hi, I have tried to run the pipeline using the code above but have encountered the issue below:

```
Traceback (most recent call last):
  File "/home/jason/git/speech-to-speech/s2s_pipeline.py", line 1017, in <module>
    main()
  File "/home/jason/git/speech-to-speech/s2s_pipeline.py", line 984, in main
    tts = ParlerTTSHandler(
  File "/home/jason/git/speech-to-speech/s2s_pipeline.py", line 103, in __init__
    self.setup(*setup_args, **setup_kwargs)
  File "/home/jason/git/speech-to-speech/s2s_pipeline.py", line 790, in setup
    self.warmup()
  File "/home/jason/git/speech-to-speech/s2s_pipeline.py", line 838, in warmup
    _ = self.model.generate(**model_kwargs)
  File "/home/jason/git/speech-to-speech/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jason/git/speech-to-speech/.venv/lib/python3.10/site-packages/parler_tts/modeling_parler_tts.py", line 3438, in generate
    outputs = self._sample(
TypeError: GenerationMixin._sample() missing 1 required positional argument: 'logits_warper'
```

Is it possible to understand what is the issue, please? I have used the requirements.txt to install the needed dependencies.

**Comment by andimarafioti** [comment]
This one I actually don't have a clue. @eustlb do you know what it could be?

**Comment by jasonngap1** [comment]
I restarted my computer and the problem went away somehow. Will be closing this issue thanks!
