### ISSUE TITLE
torch._dynamo.exc.Unsupported: Logger not supported for non-export cases

### ISSUE THREAD

**Issue by lucaslxx-coder** [huggingface/speech-to-speech#150]
Please help me.When I use this code:"python s2s_pipeline.py --lm_model_name microsoft/Phi-3-mini-4k-instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --recv_host 0.0.0.0 --send_host 0.0.0.0",an error occurred.

2024-12-10 18:41:25,151 - TTS.parler_handler - INFO - Warming up ParlerTTSHandler
The 'max_batch_size' argument of StaticCache is deprecated and will be removed in v4.46. Use the more precisely named 'batch_size' argument instead.
2024-12-10 18:41:25,241 - parler_tts.modeling_parler_tts - WARNING - `prompt_attention_mask` is specified but `attention_mask` is not. A full `attention_mask` will be created. Make sure this is the intended behaviour.
Traceback (most recent call last):
  File "/home/luxinxin/speech-to-speech/s2s_pipeline.py", line 483, in <module>
    main()
  File "/home/luxinxin/speech-to-speech/s2s_pipeline.py", line 458, in main
    pipeline_manager = build_pipeline(
                       ^^^^^^^^^^^^^^^
  File "/home/luxinxin/speech-to-speech/s2s_pipeline.py", line 282, in build_pipeline
    tts = get_tts_handler(module_kwargs, stop_event, lm_response_queue, send_audio_chunks_queue, should_listen, parler_tts_handler_kwargs, melo_tts_handler_kwargs, chat_tts_handler_kwargs, facebook_mms_tts_handler_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/speech-to-speech/s2s_pipeline.py", line 374, in get_tts_handler
    return ParlerTTSHandler(
           ^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/speech-to-speech/baseHandler.py", line 20, in __init__
    self.setup(*setup_args, **setup_kwargs)
  File "/home/luxinxin/speech-to-speech/TTS/parler_handler.py", line 100, in setup
    self.warmup()
  File "/home/luxinxin/speech-to-speech/TTS/parler_handler.py", line 158, in warmup
    _ = self.model.generate(**model_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 3561, in generate
    outputs = self._sample(
              ^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
    return _compile(
           ^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
    super().run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 1680, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 324, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 324, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/lazy.py", line 156, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/nn_module.py", line 899, in call_function
    return variables.UserFunctionVariable(fn, source=source).call_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 324, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 385, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 324, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 385, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 324, in call_function
    return super().call_function(tx, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/functions.py", line 111, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 836, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3011, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 3139, in inline_call_
    tracer.run()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 582, in wrapper
    return inner_fn(self, inst)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2279, in CALL
    self._call(inst)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2273, in _call
    self.call_function(fn, args, kwargs)
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 830, in call_function
    self.push(fn.call_function(self, args, kwargs))  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/misc.py", line 1024, in call_function
    return self.obj.call_method(tx, self.name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/variables/misc.py", line 1465, in call_method
    unimplemented("Logger not supported for non-export cases")
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 297, in unimplemented
    raise Unsupported(msg, case_name=case_name)
torch._dynamo.exc.Unsupported: Logger not supported for non-export cases

from user code:
   File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 2844, in forward
    decoder_outputs = self.decoder(
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 1895, in forward
    outputs = self.model(
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 1789, in forward
    decoder_outputs = self.decoder(
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 1538, in forward
    causal_mask = self._update_causal_mask(
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/parler_tts/modeling_parler_tts.py", line 1696, in _update_causal_mask
    target_length = past_key_values.get_max_length()
  File "/home/luxinxin/anaconda3/envs/sts/lib/python3.11/site-packages/transformers/cache_utils.py", line 72, in get_max_length
    logger.warning_once(

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by ThinkThrice** [comment]
I got the same problem. Have you fixed it ? It seems like the Logger crashed.  Also, maybe the Bug information is too long to print the Log, rather than the Logger itself.

**Comment by Microset** [comment]
We got the same problem, but with different Unsupported:
torch._dynamo.exc.Unsupported: Logger not supported for non-export cases. To avoid graph breaks caused by logger in compile-mode, it is recommended to disable logging by adding logging methods to config.ignore_logger_methods
Do you have any advice?

**Comment by andreminin** [comment]
I just started Python, my background is Java.

My findings:

the issue causes when torch is trying to compile model with enabled or not supported (custom) logging method.

In my case, I faced this error when trying to run 

`python s2s_pipeline.py \
	--lm_model_name microsoft/Phi-3-mini-4k-instruct \
	--stt_compile_mode reduce-overhead \
	--log_level debug \
	--tts_compile_mode default \
  --recv_host 0.0.0.0 \
	--send_host 0.0.0.0`

Problem was in logger method inside transformers cache_utils when torch compile detected it.

This quick patch can be used as starting point to make more elegant fix (with torch compile detection,etc) - this is my first patch in Python, just started it (my background is Java).

Added method to parler_handler.py to disable logger methods:

`    @contextmanager
    def temporarily_ignore_logger_methods(self, ignored_methods):
        config = torch._dynamo.config
        original = list(config.ignore_logger_methods)  # make a copy

        try:
            config.ignore_logger_methods.update(ignored_methods)
            yield
        finally:
            config.ignore_logger_methods = original  # restore original list
`
Imported cache_utils logger to get warning_once method reference to ignore it when compiling model :

`from transformers.utils import logging as hf_logging

# hf cache_utils logger to disable when calling model compile
hf_logger = hf_logging.get_logger("transformers.cache_utils")`


and called logger methods ignore before model forward triggered (line 168):
`        if self.compile_mode:
            pad_lengths = [2**i for i in range(2, self.max_prompt_pad_length)]
            #disable hf cache utils logger before compiling model
            with self.temporarily_ignore_logger_methods([hf_logger.warning_once]):
                for pad_length in pad_lengths[::-1]:
                    model_kwargs = self.prepare_model_inputs(
                       "dummy prompt", max_length_prompt=pad_length, pad=True
                    )
                    for _ in range(n_steps):
                        _ = self.model.generate(**model_kwargs)
                    logger.info(f"Warmed up length {pad_length} tokens!")`

Now server starts OK.


Patch (sorry, for some reason upload doesn't work):  

`Index: TTS/parler_handler.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/TTS/parler_handler.py b/TTS/parler_handler.py
--- a/TTS/parler_handler.py	(revision d33cfc5cefdb39bf2aff1483b30c186b021f5b95)
+++ b/TTS/parler_handler.py	(date 1752125643206)
@@ -14,6 +14,11 @@
 from transformers.utils.import_utils import (
     is_flash_attn_2_available,
 )
+from contextlib import contextmanager
+from transformers.utils import logging as hf_logging
+
+# hf cache_utils logger to disable when calling model compile
+hf_logger = hf_logging.get_logger("transformers.cache_utils")
 
 torch._inductor.config.fx_graph_cache = True
 # mind about this parameter ! should be >= 2 * number of padded prompt sizes for TTS
@@ -76,7 +81,7 @@
         self.model = ParlerTTSForConditionalGeneration.from_pretrained(
             model_name, torch_dtype=self.torch_dtype
         ).to(device)
-        
+
         self.description_tokenizer = AutoTokenizer.from_pretrained(self.model.config.text_encoder._name_or_path)
         self.prompt_tokenizer = AutoTokenizer.from_pretrained(model_name)
 
@@ -135,6 +140,17 @@
 
         return gen_kwargs
 
+    @contextmanager
+    def temporarily_ignore_logger_methods(self, ignored_methods):
+        config = torch._dynamo.config
+        original = list(config.ignore_logger_methods)  # make a copy
+
+        try:
+            config.ignore_logger_methods.update(ignored_methods)
+            yield
+        finally:
+            config.ignore_logger_methods = original  # restore original list
+
     def warmup(self):
         logger.info(f"Warming up {self.__class__.__name__}")
 
@@ -150,13 +166,15 @@
             start_event.record()
         if self.compile_mode:
             pad_lengths = [2**i for i in range(2, self.max_prompt_pad_length)]
-            for pad_length in pad_lengths[::-1]:
-                model_kwargs = self.prepare_model_inputs(
-                    "dummy prompt", max_length_prompt=pad_length, pad=True
-                )
-                for _ in range(n_steps):
-                    _ = self.model.generate(**model_kwargs)
-                logger.info(f"Warmed up length {pad_length} tokens!")
+            #disable hf cache utils logger before compiling model
+            with self.temporarily_ignore_logger_methods([hf_logger.warning_once]):
+                for pad_length in pad_lengths[::-1]:
+                    model_kwargs = self.prepare_model_inputs(
+                       "dummy prompt", max_length_prompt=pad_length, pad=True
+                    )
+                    for _ in range(n_steps):
+                        _ = self.model.generate(**model_kwargs)
+                    logger.info(f"Warmed up length {pad_length} tokens!")
         else:
             model_kwargs = self.prepare_model_inputs("dummy prompt")
             for _ in range(n_steps):
@@ -173,7 +191,7 @@
         if isinstance(llm_sentence, tuple):
             llm_sentence, language_code = llm_sentence
             self.speaker = WHISPER_LANGUAGE_TO_PARLER_SPEAKER.get(language_code, "Jason")
-            
+
         console.print(f"[green]ASSISTANT: {llm_sentence}")
         nb_tokens = len(self.prompt_tokenizer(llm_sentence).input_ids)
 
`
