### ISSUE TITLE
Error running on GPU: "no `device` argument is passed to the `Pipeline` object"

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/speech-to-speech#19]
### Device
A40 on Runpod

### Replication
```
git clone https://github.com/eustlb/speech-to-speech.git
cd speech-to-speech
pip install -r requirements.txt
pip install flash-attn --no-build-isolation
pip install git+https://github.com/nltk/nltk.git@3.8.2
python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --lm_device cuda --tts_device cuda --stt_device cuda
```
Error (note that the error is the same, except for notes on invalid arguments, if the `_device` arguments are omitted):
```
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
```
Remarks:
- Interestingly, audio is very choppy on a Runpod A40 but better on a H100. Perhaps this is because the cpu is inadvertently being used.

Full Logs
```
python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --lm_device cuda --tts_device cuda --stt_device cuda python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --lm_device cuda --tts_device cuda --stt_device cuda
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "/workspace/speech-to-speech/s2s_pipeline.py", line 1027, in <module>
    main()
  File "/workspace/speech-to-speech/s2s_pipeline.py", line 946, in main
    ) = parser.parse_args_into_dataclasses()
  File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 348, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['python', 's2s_pipeline.py']
root@99067bac1bf9:/workspace/speech-to-speech# python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --lm_device cuda --tts_device cuda --stt_device cuda
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Using cache found in /root/.cache/torch/hub/snakers4_silero-vad_master
2024-08-19 12:35:55,201 - __main__ - INFO - Warming up WhisperSTTHandler
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2024-08-19 12:36:21,708 - __main__ - INFO - WhisperSTTHandler:  warmed up! time: 26.504 s
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
2024-08-19 12:36:22,619 - __main__ - INFO - Warming up LanguageModelHandler
/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
2024-08-19 12:36:26,197 - __main__ - INFO - LanguageModelHandler:  warmed up! time: 3.577 s
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2024-08-19 12:36:57,306 - __main__ - INFO - Warming up ParlerTTSHandler
2024-08-19 12:36:57,368 - parler_tts.modeling_parler_tts - WARNING - `prompt_attention_mask` is specified but `attention_mask` is not. A full `attention_mask` will be created. Make sure this is the intended behaviour.
2024-08-19 12:37:24,859 - __main__ - INFO - Warmed up length 128 tokens!
2024-08-19 12:38:03,756 - __main__ - INFO - Warmed up length 64 tokens!
2024-08-19 12:38:05,989 - __main__ - INFO - Warmed up length 32 tokens!
2024-08-19 12:38:06,472 - __main__ - INFO - Warmed up length 16 tokens!
2024-08-19 12:38:07,098 - __main__ - INFO - Warmed up length 8 tokens!
2024-08-19 12:38:07,732 - __main__ - INFO - Warmed up length 4 tokens!
2024-08-19 12:38:07,732 - __main__ - INFO - ParlerTTSHandler:  warmed up! time: 70.425 s
2024-08-19 12:38:07,734 - __main__ - INFO - Receiver waiting to be connected...
2024-08-19 12:38:07,735 - __main__ - INFO - Sender waiting to be connected...
```

**Comment by andimarafioti** [comment]
Interesting! I was just working on support for it to run on a mac. Will pick this up when I'm done, thank you for raising!

**Comment by andimarafioti** [comment]
![image](https://github.com/user-attachments/assets/f83bff0e-294e-4192-86e7-2d7585007be8)

Oh wait, it's you! xD

**Comment by RonanKMcGovern** [comment]
Still seeing the same issue:
```
Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.
```
after:
```
git clone https://github.com/eustlb/speech-to-speech.git
cd speech-to-speech
pip install -r requirements.txt
pip install flash-attn --no-build-isolation
pip install git+https://github.com/nltk/nltk.git@3.8.2
python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default --lm_device cuda --tts_device cuda --stt_device cuda
```

**Comment by RonanKMcGovern** [comment]
Ok, this is running fine now with just `python s2s_pipeline.py --lm_model_name HuggingFaceTB/SmolLM-360M-Instruct --stt_compile_mode reduce-overhead --tts_compile_mode default`

BTW, the choppy audio is because of having play_steps_s too low. Around 1-1.5 seconds works better.
