### ISSUE TITLE
Installation seems to require MeCab to be installed

### ISSUE THREAD

**Issue by rchan26** [huggingface/speech-to-speech#44]
Hi - really cool project! I'm having some issues installing on M1 (I've tried `uv pip install -r requirements.txt` and `uv pip install -r requirements_mac.txt`) as it seems like I need to have MeCab installed:

```
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/rchan/.cache/uv/builds-v0/.tmpFZtNEW/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rchan/.cache/uv/builds-v0/.tmpFZtNEW/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/Users/rchan/.cache/uv/builds-v0/.tmpFZtNEW/lib/python3.12/site-packages/setuptools/build_meta.py", line 502, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/rchan/.cache/uv/builds-v0/.tmpFZtNEW/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 15, in <module>
  File "/Users/rchan/.cache/uv/built-wheels-v3/pypi/fugashi/1.3.0/DE5_JVoERHEULVkOBncXZ/fugashi-1.3.0.tar.gz/fugashi_util.py", line 58, in check_libmecab
    raise RuntimeError("Could not configure working env. Have you installed MeCab?")
RuntimeError: Could not configure working env. Have you installed MeCab?
```

It seems like `fugashi` is a dependency through [MeloTSS](https://github.com/myshell-ai/MeloTTS/blob/main/requirements.txt) which I'm having issues with. It seems like I need to install MeCab, but the installation instructions are in Japanese (https://taku910.github.io/mecab/).

Anyone else have this issue?

**Comment by rchan26** [comment]
Closing this as I was trying to install with Python 3.12 and got the above error. Installation is fine with 3.11.
