### ISSUE TITLE
Nothing happening after run

### ISSUE THREAD

**Issue by austinmw** [huggingface/speech-to-speech#47]
```bash
python s2s_pipeline.py --local_mac_optimal_settings
```

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/bcfa5d0a-7794-4878-9914-555440b09801">

It seems this is done running set up and ready for me to start speaking? My mic is set to MacBook Pro Microphone. I say something, but nothing happens.

Not sure if the setup has hung or what?

**Comment by andimarafioti** [comment]
That looks alright, are you sure your microphone is working properly? I would wait a few seconds and say something loudly

**Comment by austinmw** [comment]
I think so.. I checked that the input is working in Mac sound settings, and shouted loudly for a minute or so 😅

I wonder if maybe logging messages can be added for these?
- Successfully initialized and waiting for speech
- Mic input selection

**Comment by andimarafioti** [comment]
That makes sense, I'll add more Debug messages tomorrow and get back to you

**Comment by andimarafioti** [comment]
pull the changes before 😅

**Comment by andimarafioti** [comment]
This is what it looks like for me.
```python
 python s2s_pipeline.py --local_mac_optimal_settings --log_level DEBUG
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/andresmarafioti/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
Using cache found in /Users/andresmarafioti/.cache/torch/hub/snakers4_silero-vad_master
2024-08-27 15:28:22,882 - torio._extension.utils - DEBUG - Loading FFmpeg6
2024-08-27 15:28:22,884 - torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so, 0x0006): Library not loaded: @rpath/libavutil.58.dylib
  Referenced from: <0751190B-95A9-3BBA-8A30-48A0E705FE4E> /Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg6.so
  Reason: tried: '/opt/homebrew/lib/libavutil.58.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libavutil.58.dylib' (no such file)
2024-08-27 15:28:22,885 - torio._extension.utils - DEBUG - Loading FFmpeg5
2024-08-27 15:28:22,887 - torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so, 0x0006): Library not loaded: @rpath/libavutil.57.dylib
  Referenced from: <6A4BDCC0-2B86-3C3E-8CC4-A5F46798C33F> /Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg5.so
  Reason: tried: '/opt/homebrew/lib/libavutil.57.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libavutil.57.dylib' (no such file)
2024-08-27 15:28:22,887 - torio._extension.utils - DEBUG - Loading FFmpeg4
2024-08-27 15:28:22,889 - torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torch/_ops.py", line 1295, in load_library
    ctypes.CDLL(path)
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so, 0x0006): Library not loaded: @rpath/libavutil.56.dylib
  Referenced from: <36E35F5C-1717-3BAC-84FC-DD4CA5107A3E> /Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/lib/libtorio_ffmpeg4.so
  Reason: tried: '/opt/homebrew/lib/libavutil.56.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libavutil.56.dylib' (no such file)
2024-08-27 15:28:22,889 - torio._extension.utils - DEBUG - Loading FFmpeg
2024-08-27 15:28:22,889 - torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torio/_extension/utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
2024-08-27 15:28:23,072 - filelock - DEBUG - Attempting to acquire lock 5003841296 on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,072 - filelock - DEBUG - Lock 5003841296 acquired on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,073 - filelock - DEBUG - Attempting to release lock 5003841296 on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,073 - filelock - DEBUG - Lock 5003841296 released on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,074 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
2024-08-27 15:28:23,239 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /mustafaaljadery/distil-whisper-mlx/resolve/main/mlx_models/distil-large-v3/weights.npz HTTP/11" 302 0
2024-08-27 15:28:23,241 - filelock - DEBUG - Attempting to acquire lock 5003844304 on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,241 - filelock - DEBUG - Lock 5003844304 acquired on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,241 - filelock - DEBUG - Attempting to release lock 5003844304 on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,241 - filelock - DEBUG - Lock 5003844304 released on .cache/huggingface/download/mlx_models/distil-large-v3/weights.npz.lock
2024-08-27 15:28:23,241 - filelock - DEBUG - Attempting to acquire lock 5003853328 on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,241 - filelock - DEBUG - Lock 5003853328 acquired on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,242 - filelock - DEBUG - Attempting to release lock 5003853328 on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,242 - filelock - DEBUG - Lock 5003853328 released on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,363 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /mustafaaljadery/distil-whisper-mlx/resolve/main/mlx_models/distil-large-v3/config.json HTTP/11" 200 0
2024-08-27 15:28:23,364 - filelock - DEBUG - Attempting to acquire lock 5003911760 on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,365 - filelock - DEBUG - Lock 5003911760 acquired on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,365 - filelock - DEBUG - Attempting to release lock 5003911760 on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,366 - filelock - DEBUG - Lock 5003911760 released on .cache/huggingface/download/mlx_models/distil-large-v3/config.json.lock
2024-08-27 15:28:23,366 - STT.lightning_whisper_mlx_handler - INFO - Warming up LightningWhisperSTTHandler
2024-08-27 15:28:26,619 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/mlx-community/SmolLM-360M-Instruct/revision/main HTTP/11" 200 2542
Fetching 9 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 20493.34it/s]
mlx_lm.models.llama
2024-08-27 15:28:27,232 - LLM.mlx_language_model - INFO - Warming up MLXLanguageModelHandler
2024-08-27 15:28:29,957 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /tohoku-nlp/bert-base-japanese-v3/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:30,746 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:30,921 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /bert-base-multilingual-uncased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:31,120 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /kykim/bert-kor-base/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:31,502 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /dbmdz/bert-base-french-europeana-cased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:31,656 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /dccuchile/bert-base-spanish-wwm-uncased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:32,057 - google.cloud.storage._opentelemetry_tracing - DEBUG - This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get Storage Tracing data.
2024-08-27 15:28:32,227 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /myshell-ai/MeloTTS-English-v3/resolve/main/config.json HTTP/11" 200 0
/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2024-08-27 15:28:32,813 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /myshell-ai/MeloTTS-English-v3/resolve/main/checkpoint.pth HTTP/11" 302 0
/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/melo/download_utils.py:64: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(ckpt_path, map_location=device)
2024-08-27 15:28:33,082 - TTS.melo_handler - INFO - Warming up MeloTTSHandler
2024-08-27 15:28:33,214 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:33,351 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /dccuchile/bert-base-spanish-wwm-uncased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:33,492 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /dbmdz/bert-base-french-europeana-cased/resolve/main/tokenizer_config.json HTTP/11" 200 0
2024-08-27 15:28:33,660 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/config.json HTTP/11" 200 0
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
A parameter name that contains `beta` will be renamed internally to `bias`. Please use a different name to suppress this warning.
A parameter name that contains `gamma` will be renamed internally to `weight`. Please use a different name to suppress this warning.
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
2024-08-27 15:28:34,267 - urllib3.connectionpool - DEBUG - https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/generation_config.json HTTP/11" 404 0
/Users/andresmarafioti/Documents/speech-to-speech/.venv/lib/python3.11/site-packages/torch/nn/functional.py:4552: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:472.)
  return torch._C._nn.pad(input, pad, mode, value)
2024-08-27 15:28:36,473 - connections.local_audio_streamer - DEBUG - Available devices:
2024-08-27 15:28:36,473 - connections.local_audio_streamer - DEBUG -   0 DELL U3425WE, Core Audio (0 in, 2 out)
  1 Andi’s iPhone Microphone, Core Audio (1 in, 0 out)
  2 Background Music, Core Audio (2 in, 2 out)
  3 Background Music (UI Sounds), Core Audio (2 in, 2 out)
  4 MacBook Pro Microphone, Core Audio (1 in, 0 out)
  5 MacBook Pro Speakers, Core Audio (0 in, 2 out)
> 6 Andi's AirPods Pro, Core Audio (1 in, 0 out)
< 7 Andi's AirPods Pro, Core Audio (0 in, 2 out)
  8 LoomAudioDevice, Core Audio (2 in, 2 out)
2024-08-27 15:28:36,835 - connections.local_audio_streamer - INFO - Starting local audio stream
2024-08-27 15:28:53,911 - VAD.vad_handler - DEBUG - VAD: end of speech detected
2024-08-27 15:28:53,911 - VAD.vad_handler - DEBUG - Stop listening
2024-08-27 15:28:53,911 - baseHandler - DEBUG - VADHandler:  0.002 s
2024-08-27 15:28:53,911 - STT.lightning_whisper_mlx_handler - DEBUG - infering whisper...
2024-08-27 15:28:55,473 - STT.lightning_whisper_mlx_handler - DEBUG - finished whisper inference
USER: How are you doing?
2024-08-27 15:28:55,474 - baseHandler - DEBUG - LightningWhisperSTTHandler:  1.563 s
2024-08-27 15:28:55,474 - LLM.mlx_language_model - DEBUG - infering language model...
2024-08-27 15:28:55,623 - baseHandler - DEBUG - MLXLanguageModelHandler:  0.149 s
ASSISTANT: I'm doing well, thanks for asking!
2024-08-27 15:28:56,419 - baseHandler - DEBUG - MeloTTSHandler:  0.796 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
2024-08-27 15:28:56,420 - baseHandler - DEBUG - MeloTTSHandler:  0.000 s
```

**Comment by austinmw** [comment]
Thanks, will test ASAP!
