### ISSUE TITLE
unable to establish connection and making a request to server

### ISSUE THREAD

**Issue by Devloper-RG** [huggingface/speech-to-speech#75]
My server(s2s_pipeline.py) is `running` fine on a GCP VM, have changed all recv_port and send_port on "listen_and_play.py" script, but on running "python listen_and_play.py --host <External IP address of my VM>"  on my local system i am unable connect and make request to the server and getting following error:
getting error- 
```
Traceback (most recent call last):
  File "S:\speech-to-speech-main\listen_and_play.py", line 126, in <module>
    listen_and_play(**vars(listen_and_play_kwargs))
  File "S:\speech-to-speech-main\listen_and_play.py", line 42, in listen_and_play
    send_socket.connect((host, send_port))
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

Note: the ports I am using is configured on firewall rules on my VM.

pls help me with establishing connection and making request to server via my windows system.

**Comment by rs545837** [comment]
The default ports, 12345 and 12346 needs to be exposed on your gcp instance, to connect it with the local client.

**Comment by Devloper-RG** [comment]
I successfully exposed the predefined ports (12345 and 12346) and was able to interact with the server. However, I would now like to use new ports. What changes are required in the configuration/code to allow the server to run on different ports?

**Comment by rs545837** [comment]
Use the `--recv_port` and `--send_port` arguments for using ports other than 12345 and 12346.

**Comment by Devloper-RG** [comment]
I tried this but was unable to interact with the server.

**Comment by rs545837** [comment]
Hey @Devloper-RG, could you please send the commands that you have been using on the server and client? I may be able to help you better.

**Comment by Devloper-RG** [comment]
terminal commands
client side : python listen_and_play.py --host <IP address> --send_port 3001 --recv_port 3002
server side : python s2s_pipeline.py --recv_host 0.0.0.0 --send_host 0.0.0.0

and i also made sure these ports were exposed on my gcp instance
