### ISSUE TITLE
Exception :  Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by SaddamBInSyed** [huggingface/speech-to-speech#86]
Hi ,

@andimarafioti 

when i run the  "python s2s_pipeline.py" with mentioned arguments in teh readme file ,  When i started to speak I am getting the below exception 

(/home/user/Downloads/speech-to-speech/sts) ~/PycharmProjects/speech-to-speech git:[multi-language]
python s2s_pipeline.py 	--recv_host 0.0.0.0 	--send_host 0.0.0.0 	--lm_model_name microsoft/Phi-3-mini-4k-instruct 	--init_chat_role system 	--stt_compile_mode reduce-overhead 	--tts_compile_mode default
/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/user/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
Using cache found in /home/user/.cache/torch/hub/snakers4_silero-vad_master
2024-09-05 14:53:45,040 - STT.whisper_stt_handler - INFO - Warming up WhisperSTTHandler
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
2024-09-05 14:54:06,376 - STT.whisper_stt_handler - INFO - WhisperSTTHandler:  warmed up! time: 21.336 s
2024-09-05 14:54:07,457 - transformers_modules.microsoft.Phi-3-mini-4k-instruct.5a516f86087853f9d560c95eb9209c1d4ed9ff69.modeling_phi3 - WARNING - `flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
2024-09-05 14:54:07,457 - transformers_modules.microsoft.Phi-3-mini-4k-instruct.5a516f86087853f9d560c95eb9209c1d4ed9ff69.modeling_phi3 - WARNING - Current `flash-attention` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.16s/it]
2024-09-05 14:54:11,049 - LLM.language_model - INFO - Warming up LanguageModelHandler
/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
2024-09-05 14:54:11,113 - transformers_modules.microsoft.Phi-3-mini-4k-instruct.5a516f86087853f9d560c95eb9209c1d4ed9ff69.modeling_phi3 - WARNING - You are not running the flash-attention implementation, expect numerical differences.
2024-09-05 14:54:11,263 - LLM.language_model - INFO - LanguageModelHandler:  warmed up! time: 0.214 s
2024-09-05 14:54:11,383 - parler_tts.modeling_parler_tts - WARNING - Flash attention 2 is not installed
2024-09-05 14:54:11,551 - TTS.parler_handler - WARNING - Parler TTS works best with flash attention 2, but is not installed
        Given that CUDA is available in this system, you can install flash attention 2 with `uv pip install flash-attn --no-build-isolation`
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
2024-09-05 14:54:37,955 - TTS.parler_handler - INFO - Warming up ParlerTTSHandler
2024-09-05 14:54:37,990 - parler_tts.modeling_parler_tts - WARNING - `prompt_attention_mask` is specified but `attention_mask` is not. A full `attention_mask` will be created. Make sure this is the intended behaviour.
2024-09-05 14:55:00,466 - TTS.parler_handler - INFO - Warmed up length 128 tokens!
2024-09-05 14:55:45,284 - TTS.parler_handler - INFO - Warmed up length 64 tokens!
2024-09-05 14:55:46,336 - TTS.parler_handler - INFO - Warmed up length 32 tokens!
2024-09-05 14:55:46,995 - TTS.parler_handler - INFO - Warmed up length 16 tokens!
2024-09-05 14:55:48,776 - TTS.parler_handler - INFO - Warmed up length 8 tokens!
2024-09-05 14:55:49,682 - TTS.parler_handler - INFO - Warmed up length 4 tokens!
2024-09-05 14:55:49,682 - TTS.parler_handler - INFO - ParlerTTSHandler:  warmed up! time: 71.728 s
2024-09-05 14:55:49,682 - connections.socket_sender - INFO - Sender waiting to be connected...
2024-09-05 14:55:49,683 - connections.socket_receiver - INFO - Receiver waiting to be connected...
2024-09-05 14:55:57,632 - connections.socket_receiver - INFO - receiver connected
2024-09-05 14:55:57,632 - connections.socket_sender - INFO - sender connected
USER:  Hello, how are you?
/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
ASSISTANT: ('Hello!', 'en')
Exception in thread Thread-12 (generate):
Traceback (most recent call last):
  File "/home/user/Downloads/speech-to-speech/sts/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/Downloads/speech-to-speech/sts/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/parler_tts/modeling_parler_tts.py", line 3316, in generate
    input_ids, model_kwargs = self._prepare_decoder_input_ids_for_generation(
  File "/home/user/Downloads/speech-to-speech/sts/lib/python3.10/site-packages/parler_tts/modeling_parler_tts.py", line 2923, in _prepare_decoder_input_ids_for_generation
    inputs_embeds = torch.cat([prompt_hidden_states, inputs_embeds], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 1 for tensor number 1 in the list.

**Comment by andimarafioti** [comment]
I'm looking into it

**Comment by andimarafioti** [comment]
Fixed it, thank you for raising it 🙏
